### ISSUE TITLE
Problem in diff widget

### ISSUE THREAD

**Issue by skarllot** [hasselmm/giggle#1]
When in History mode, select a commit which contains deleted binary files or empty added files (propably any modification that returns empty diff).
When any these files with empty diff the diff widget remains with last diff.
The diff widget should be cleaned to indicate an empty diff.

**Comment by skarllot** [comment]
I'm using 0.4.91 version.

**Comment by guyou** [comment]
It is better to use the Gnome bug tracker to open issues on giggle: http://bugzilla.gnome.org/browse.cgi?product=giggle

Furthermore, I think your bug is related to the following known issue:
http://bugzilla.gnome.org/show_bug.cgi?id=575450
